-- customer table
CREATE TABLE CUSTOMER (
    CUST_NO CHAR(5) NOT NULL CHECK (CUST_NO LIKE 'C____'),
    NAME VARCHAR(50) NOT NULL,
    PHONE_NO CHAR(10),
    CITY VARCHAR(50) NOT NULL,
    PRIMARY KEY (CUST_NO)
);
INSERT INTO CUSTOMER (CUST_NO, NAME, PHONE_NO, CITY)
VALUES 
('C0001', 'RAJ ANAND SINGH', '9861258466', 'DELHI'),
('C0002', 'ANKITA SINGH', '9879958651', 'BANGALORE'),
('C0003', 'SOUMYA JHA', '9885623344', 'MUMBAI'),
('C0004', 'ABHIJIT MISHRA', '9455845425', 'MUMBAI'),
('C0005', 'YASH SARAF', '9665854585', 'KOLKATA'),
('C0006', 'SWAROOP RAY', '9437855466', 'CHENNAI'),
('C0007', 'SURYA NARAYAN', '9937955212', 'GURGAON'),
('C0008', 'PRANAV PRAVEEN', '9336652441', 'PUNE'),
('C0009', 'STUTI MISRA', '7870266534', 'DELHI'),
('C0010', 'ASLESHA TIWARI', NULL, 'MUMBAI'); -- NULL used for missing PHONE_NO

-- account table
-- CREATE TABLE ACCOUNT (
--     ACCOUNT_NO CHAR(5) NOT NULL CHECK (ACCOUNT_NO LIKE 'A____'),
--     TYPE CHAR(2) CHECK (TYPE IN ('SB', 'FD', 'CA')),
--     BALANCE NUMERIC(10,2) CHECK (BALANCE < 10000000),
--     BRANCH_CODE CHAR(5),
--     PRIMARY KEY (ACCOUNT_NO),
--     FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE)
-- );

CREATE TABLE ACCOUNT (
    ACCOUNT_NO CHAR(5) NOT NULL CHECK (ACCOUNT_NO LIKE 'A____'),
    TYPE CHAR(2) CHECK (TYPE IN ('SB', 'FD', 'CA')),
    BALANCE NUMERIC(10,2) CHECK (BALANCE < 10000000),
    BRANCH_CODE CHAR(5),
    PRIMARY KEY (ACCOUNT_NO),
    FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE)
);

-- depositor
CREATE TABLE DEPOSITOR (
    CUST_NO CHAR(5) NOT NULL,
    ACCOUNT_NO CHAR(5) NOT NULL,
    PRIMARY KEY (CUST_NO, ACCOUNT_NO),
    FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER(CUST_NO),
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NO)
);
-- Loan
CREATE TABLE LOAN (
    LOAN_NO CHAR(5) NOT NULL CHECK (LOAN_NO LIKE 'L____'),
    CUST_NO CHAR(5) NOT NULL,
    AMOUNT NUMERIC(10,2) CHECK (AMOUNT > 1000),
    BRANCH_CODE CHAR(5),
    PRIMARY KEY (LOAN_NO),
    FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER(CUST_NO),
    FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE)
);
-- branch
CREATE TABLE BRANCH (
    BRANCH_CODE CHAR(5) NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    BRANCH_CITY VARCHAR(50) CHECK (BRANCH_CITY IN ('DELHI', 'MUMBAI', 'KOLKATA', 'CHENNAI')),
    PRIMARY KEY (BRANCH_CODE)
);
-- Installment
CREATE TABLE INSTALLMENT (
    INST_NO INT NOT NULL CHECK (INST_NO <= 10),
    LOAN_NO CHAR(5) NOT NULL,
    INST_AMOUNT NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (INST_NO, LOAN_NO),
    FOREIGN KEY (LOAN_NO) REFERENCES LOAN(LOAN_NO)
);
